# Generated by Django 5.2.7 on 2025-10-18 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=12, unique=True, verbose_name='ИНН')),
                ('name', models.CharField(max_length=500, verbose_name='Наименование организации')),
                ('full_name', models.CharField(blank=True, max_length=1000, verbose_name='Полное наименование организации')),
                ('status', models.CharField(blank=True, max_length=200, verbose_name='Статус')),
                ('legal_address', models.TextField(blank=True, verbose_name='Юридический адрес')),
                ('production_address', models.TextField(blank=True, verbose_name='Адрес производства')),
                ('additional_site_address', models.TextField(blank=True, verbose_name='Адрес дополнительной площадки')),
                ('main_industry', models.CharField(blank=True, max_length=200, verbose_name='Основная отрасль')),
                ('main_subindustry', models.CharField(blank=True, max_length=200, verbose_name='Подотрасль (Основная)')),
                ('main_okved', models.CharField(blank=True, max_length=20, verbose_name='Основной ОКВЭД')),
                ('main_okved_desc', models.CharField(blank=True, max_length=500, verbose_name='Вид деятельности по основному ОКВЭД')),
                ('production_okved', models.CharField(blank=True, max_length=20, verbose_name='Производственный ОКВЭД')),
                ('registration_date', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('head', models.CharField(blank=True, max_length=300, verbose_name='Руководитель')),
                ('parent_company', models.CharField(blank=True, max_length=500, verbose_name='Головная организация')),
                ('parent_inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН головной организации')),
                ('head_contacts', models.TextField(blank=True, verbose_name='Контактные данные руководства')),
                ('staff_contact', models.TextField(blank=True, verbose_name='Контакт сотрудника организации')),
                ('emergency_contact', models.TextField(blank=True, verbose_name='Контактные данные ответственного по ЧС')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('support_measures', models.TextField(blank=True, verbose_name='Данные об оказанных мерах поддержки')),
                ('special_status', models.CharField(blank=True, max_length=200, verbose_name='Наличие особого статуса')),
                ('is_msp', models.BooleanField(default=False, verbose_name='Статус МСП')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeoLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_legal', models.FloatField(blank=True, null=True, verbose_name='Координаты юридического адреса (широта)')),
                ('lon_legal', models.FloatField(blank=True, null=True, verbose_name='Координаты юридического адреса (долгота)')),
                ('lat_production', models.FloatField(blank=True, null=True, verbose_name='Координаты адреса производства (широта)')),
                ('lon_production', models.FloatField(blank=True, null=True, verbose_name='Координаты адреса производства (долгота)')),
                ('lat_additional', models.FloatField(blank=True, null=True, verbose_name='Координаты адреса дополнительной площадки (широта)')),
                ('lon_additional', models.FloatField(blank=True, null=True, verbose_name='Координаты адреса дополнительной площадки (долгота)')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Район')),
                ('okrug', models.CharField(blank=True, max_length=100, verbose_name='Округ')),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='geo_location', to='enterprises.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standardized_product', models.TextField(blank=True, verbose_name='Стандартизированная продукция')),
                ('product_names', models.TextField(blank=True, verbose_name='Название (виды производимой продукции)')),
                ('okpd2_codes', models.TextField(blank=True, verbose_name='Перечень производимой продукции по кодам ОКПД 2')),
                ('product_types_segments', models.TextField(blank=True, verbose_name='Перечень производимой продукции по типам и сегментам')),
                ('product_catalog', models.TextField(blank=True, verbose_name='Каталог продукции')),
                ('has_gov_contract', models.BooleanField(default=False, verbose_name='Наличие госзаказа')),
                ('capacity_utilization', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Уровень загрузки производственных мощностей')),
                ('exports_available', models.BooleanField(default=False, verbose_name='Наличие поставок продукции на экспорт')),
                ('export_volume_prev_year', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Объем экспорта (млн руб.) за предыдущий календарный год')),
                ('export_countries', models.TextField(blank=True, verbose_name='Перечень государств-импортеров')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_info', to='enterprises.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number_zu', models.CharField(blank=True, max_length=100, verbose_name='Кадастровый номер ЗУ')),
                ('area_zu', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Площадь ЗУ')),
                ('permitted_use_zu', models.CharField(blank=True, max_length=500, verbose_name='Вид разрешенного использования ЗУ')),
                ('ownership_type_zu', models.CharField(blank=True, max_length=200, verbose_name='Вид собственности ЗУ')),
                ('owner_zu', models.CharField(blank=True, max_length=500, verbose_name='Собственник ЗУ')),
                ('cadastral_number_oks', models.CharField(blank=True, max_length=100, verbose_name='Кадастровый номер ОКСа')),
                ('area_oks', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Площадь ОКСов')),
                ('permitted_use_oks', models.CharField(blank=True, max_length=500, verbose_name='Вид разрешенного использования ОКСов')),
                ('construction_type_oks', models.CharField(blank=True, max_length=500, verbose_name='Тип строения и цель использования')),
                ('ownership_type_oks', models.CharField(blank=True, max_length=200, verbose_name='Вид собственности ОКСов')),
                ('owner_oks', models.CharField(blank=True, max_length=500, verbose_name='Собственник ОКСов')),
                ('production_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Площадь производственных помещений, кв.м.')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_info', to='enterprises.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(choices=[(2022, 2022), (2023, 2023), (2024, 2024)], verbose_name='Год')),
                ('revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Выручка предприятия, тыс. руб.')),
                ('net_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Чистая прибыль (убыток), тыс. руб.')),
                ('staff_total', models.IntegerField(blank=True, null=True, verbose_name='Среднесписочная численность персонала (всего по компании), чел')),
                ('staff_moscow', models.IntegerField(blank=True, null=True, verbose_name='Среднесписочная численность персонала, работающего в Москве, чел')),
                ('payroll_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Фонд оплаты труда всех сотрудников организации, тыс. руб')),
                ('payroll_moscow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Фонд оплаты труда сотрудников, работающих в Москве, тыс. руб')),
                ('avg_salary_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Средняя з.п. всех сотрудников организации, тыс.руб.')),
                ('avg_salary_moscow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Средняя з.п. сотрудников, работающих в Москве, тыс.руб.')),
                ('taxes_moscow_total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Налоги, уплаченные в бюджет Москвы (без акцизов), тыс.руб.')),
                ('tax_profit', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Налог на прибыль, тыс.руб.')),
                ('tax_property', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Налог на имущество, тыс.руб.')),
                ('tax_land', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Налог на землю, тыс.руб.')),
                ('tax_ndfl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='НДФЛ, тыс.руб.')),
                ('tax_transport', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Транспортный налог, тыс.руб.')),
                ('tax_other', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Прочие налоги')),
                ('tax_excise', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Акцизы, тыс. руб.')),
                ('investments_moscow', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Инвестиции в Мск, тыс. руб.')),
                ('export_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Объем экспорта, тыс. руб.')),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_kpis', to='enterprises.enterprise')),
            ],
            options={
                'verbose_name': 'Финансовый показатель',
                'verbose_name_plural': 'Финансовые показатели',
                'unique_together': {('enterprise', 'year')},
            },
        ),
    ]
